apiVersion: apps/v1
kind: Deployment
metadata:
  name: acr    
  namespace: kubi
  labels:
    app: dotnetdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetdemo
  template:
    metadata:
      labels:
        app: dotnetdemo
    spec:
      containers:
      - name: dotnetdemo
        image: service01.azurecr.io/dotnet-web
        ports:
        - containerPort: 5000
      imagePullSecret:
        -name: kubin
      
   
